all: Programa

Programa: FuncionesCC centroComercial
	gcc -o centroComercial.o FuncionesCC.o	

FuncionesCC: FuncionesCC.c FuncionesCC.h
	gcc -c FuncionesCC.c

Main: centroComercial.c FuncionesCC.c
	gcc -c centroComercial.c
